`ServiceAccountAccess::get_token_with`
EmbarkStudios/tame-oauth pull request #38
Opened 2021-06-07 20:45 UTC by fosskers

This PR exposes the new method `get_token_with` for control over the JWT "subject" field. This is necessary when interacting with the Gmail API via a Service Account, since Google requires that the **email address of the person you want to fetch emails for (etc) be included in the token creation process**. 

This PR has been tested and solves the "Failed precondition check" problem that has plagued a number of people over the years.

**Note:** Looking at the code, it seems to me that `Token` caching won't work correctly if different tokens have been fetched via `get_token_with`, since cache collision is based on the Access Scopes only. This should probably be considered a bug, and perhaps fixed in this PR. Thoughts?

2021-06-07 21:27 UTC, Jake-Shadle requested changes

2021-06-07 21:27 UTC, Jake-Shadle commented on src/gcp/mod.rs
> +    pub fn get_token_with<'a, S, I, T>(
I think this should be named `get_token_with_subject`

2021-06-07 21:27 UTC, Jake-Shadle commented on src/gcp/mod.rs
> +    {
This could be made `#[inline]` now since it just delegates.

2021-06-14 19:41 UTC, fosskers commented
I've addressed the suggestions.

2021-06-18 09:25 UTC, Jake-Shadle approved these changes
Great, thanks, sorry for the delay!

2021-06-18 09:25 UTC, merged